/* Generated By:JavaCC: Do not edit this line. NFConfigParserConstants.java */
package gazoduc.config;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NFConfigParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int BLOCK = 6;
  /** RegularExpression Id. */
  int SINGLE_QUOTE_LITERAL = 7;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_LITERAL = 8;
  /** RegularExpression Id. */
  int OBRACKET = 9;
  /** RegularExpression Id. */
  int CBRACKET = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int DOT = 12;
  /** RegularExpression Id. */
  int EQ = 13;
  /** RegularExpression Id. */
  int OPAR = 14;
  /** RegularExpression Id. */
  int CPAR = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int SIGN = 18;
  /** RegularExpression Id. */
  int EXPONENT = 19;
  /** RegularExpression Id. */
  int DOUBLE = 20;
  /** RegularExpression Id. */
  int BOOLEAN = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int INCLUDE_CONFIG = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "<BLOCK>",
    "<SINGLE_QUOTE_LITERAL>",
    "<DOUBLE_QUOTE_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\".\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "<DIGIT>",
    "<INT>",
    "<SIGN>",
    "<EXPONENT>",
    "<DOUBLE>",
    "<BOOLEAN>",
    "<LETTER>",
    "\"includeConfig\"",
    "<IDENTIFIER>",
  };

}
